from enum import Enum



class MessageCode(Enum):
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    PHONE_NUMBER_ALREADY_EXISTS = "PHONE_NUMBER_ALREADY_EXISTS"
    NO_COMPANY_CREATED = "NO_COMPANY_CREATED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_USER_INPUT = "INVALID_USER_INPUT"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    INVALID_ROLE = "INVALID_ROLE"
    INVALID_CODE = "INVALID_CODE"
    INVALID_USERNAME_OR_PASSWORD = "INVALID_USERNAME_OR_PASSWORD"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_USERNAME = "INVALID_USERNAME"
    INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER"
    NOT_STRONG_CUSTOMER_PASSWORD = "NOT_STRONG_CUSTOMER_PASSWORD"
    NOT_STRONG_PASSWORD = "NOT_STRONG_PASSWORD"
    INVALID_TOKEN = "INVALID_TOKEN"
    FORBIDDEN = "FORBIDDEN"
    CREATE_MANAGER_ACCOUNT_FIRST = "CREATE_MANAGER_ACCOUNT_FIRST"
    NOT_FOUND = "NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    

class ConfigKey(Enum):
    MAX_IMAGE_FILE_SIZE_MB = "MAX_IMAGE_FILE_SIZE_MB"
    ALLOWED_IMAGE_TYPES = "ALLOWED_IMAGE_TYPES"
    ALLOWED_VIDEO_TYPES = "ALLOWED_VIDEO_TYPES"
    IMAGES_BUCKET_NAME = "IMAGES_BUCKET_NAME"
    VIDEOS_BUCKET_NAME = "VIDEOS_BUCKET_NAME"
    CUSTOMER_ACCESS_TOKEN_EXP_HOURS = "CUSTOMER_ACCESS_TOKEN_EXP_HOURS"
    CUSTOMER_REFRESH_TOKEN_EXP_DAYS = "CUSTOMER_REFRESH_TOKEN_EXP_DAYS"
    MANAGER_ACCESS_TOKEN_EXP_HOURS = "MANAGER_ACCESS_TOKEN_EXP_HOURS"
    MANAGER_REFRESH_TOKEN_EXP_DAYS = "MANAGER_REFRESH_TOKEN_EXP_DAYS"
    ADMIN_ACCESS_TOKEN_EXP_HOURS = "ADMIN_ACCESS_TOKEN_EXP_HOURS"
    ADMIN_REFRESH_TOKEN_EXP_DAYS = "ADMIN_REFRESH_TOKEN_EXP_DAYS"
    MAX_VALIDATION_CODE_RESEND_ATTEMPTS = "MAX_VALIDATION_CODE_RESEND_ATTEMPTS"
    
class ManagerCompanyPermission(Enum):
    EDIT_COMPANY = "0"
    INVITE_MANAGERS = "1"
    VIEW_MANAGERS = "2"
    REMOVE_MANAGERS = "3"
    CREATE_PRODUCT = "4"
    VIEW_PRODUCT = "5"
    EDIT_PRODUCT = "6"
    REMOVE_PRODUCT = "7"



class Severity(Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"

class UserType(Enum):
    MANAGER = "manager"
    CUSTOMER = "customer"


class CompanyType(Enum):
    BOOK_STORE = "BOOK_STORE"

class OrderType(Enum):
    ASC = "ASC"
    DESC = "DESC"
    
class ManagerLevel(Enum):
    OWNER = "OWNER"
    COMPANY = "COMPANY"

class InviteStatus(Enum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"

class UploadFileType(Enum):
    IMAGE = "image"
    VIDEO = 'video'

